package inlamningsuppgift04;

//Dennis Holm
//2024-03-07

public class Inlamningsuppgift04 extends javax.swing.JFrame {
    // skapar en slumpgenerator som vi använder i de olika metoderna.
    java.util.Random random = new java.util.Random();
    /* Skapar två variabler som håller reda på datorns respektive
    spelarens antal vinster. */
    int nrComputerWin = 0;
    int nrHumanWin = 0;

    public Inlamningsuppgift04() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRockPaperScissor = new javax.swing.JPanel();
        lblRockTitle = new javax.swing.JLabel();
        lblScissorsTitle = new javax.swing.JLabel();
        lblPaperTitle = new javax.swing.JLabel();
        lblComputerChoice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txfResult = new javax.swing.JTextField();
        btnScissors = new javax.swing.JButton();
        btnRock = new javax.swing.JButton();
        btnPaper = new javax.swing.JButton();
        lblRockPaperScissor = new javax.swing.JLabel();
        pnlMyResult = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMyResult = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        lblAuthor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inlämningsuppgift 4");

        pnlRockPaperScissor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblRockTitle.setText("STEN");

        lblScissorsTitle.setText("SAX");

        lblPaperTitle.setText("PÅSE");

        lblComputerChoice.setEditable(false);

        jLabel2.setText("Datorn valde");

        txfResult.setEditable(false);

        btnScissors.setIcon(new javax.swing.ImageIcon("C:\\Users\\dehol\\Documents\\Dempan\\Programmering 1\\Grafiskt\\Sax.png")); // NOI18N
        btnScissors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScissorsActionPerformed(evt);
            }
        });

        btnRock.setIcon(new javax.swing.ImageIcon("C:\\Users\\dehol\\Documents\\Dempan\\Programmering 1\\Grafiskt\\Sten.png")); // NOI18N
        btnRock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRockActionPerformed(evt);
            }
        });

        btnPaper.setIcon(new javax.swing.ImageIcon("C:\\Users\\dehol\\Documents\\Dempan\\Programmering 1\\Grafiskt\\Påse.png")); // NOI18N
        btnPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaperActionPerformed(evt);
            }
        });

        lblRockPaperScissor.setText("Sten, sax eller påse    Först till tre vinner");

        javax.swing.GroupLayout pnlRockPaperScissorLayout = new javax.swing.GroupLayout(pnlRockPaperScissor);
        pnlRockPaperScissor.setLayout(pnlRockPaperScissorLayout);
        pnlRockPaperScissorLayout.setHorizontalGroup(
            pnlRockPaperScissorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRockPaperScissorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRockPaperScissorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRockPaperScissorLayout.createSequentialGroup()
                        .addComponent(lblRockPaperScissor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRockPaperScissorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlRockPaperScissorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlRockPaperScissorLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2)
                                .addGap(8, 8, 8)
                                .addComponent(lblComputerChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRockPaperScissorLayout.createSequentialGroup()
                                .addGroup(pnlRockPaperScissorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRock, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlRockPaperScissorLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(lblRockTitle)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlRockPaperScissorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlRockPaperScissorLayout.createSequentialGroup()
                                        .addComponent(btnScissors, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRockPaperScissorLayout.createSequentialGroup()
                                        .addComponent(lblScissorsTitle)
                                        .addGap(41, 41, 41)))
                                .addGroup(pnlRockPaperScissorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlRockPaperScissorLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(lblPaperTitle))))
                            .addComponent(txfResult))
                        .addGap(167, 167, 167))))
        );
        pnlRockPaperScissorLayout.setVerticalGroup(
            pnlRockPaperScissorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRockPaperScissorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRockPaperScissor)
                .addGap(18, 18, 18)
                .addGroup(pnlRockPaperScissorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPaper, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRock, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnScissors, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlRockPaperScissorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRockPaperScissorLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblRockTitle))
                    .addGroup(pnlRockPaperScissorLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblPaperTitle))
                    .addGroup(pnlRockPaperScissorLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblScissorsTitle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRockPaperScissorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComputerChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRockPaperScissorLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlMyResult.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txaMyResult.setEditable(false);
        txaMyResult.setColumns(20);
        txaMyResult.setRows(5);
        jScrollPane1.setViewportView(txaMyResult);

        jLabel3.setText("Mina resultat");

        javax.swing.GroupLayout pnlMyResultLayout = new javax.swing.GroupLayout(pnlMyResult);
        pnlMyResult.setLayout(pnlMyResultLayout);
        pnlMyResultLayout.setHorizontalGroup(
            pnlMyResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMyResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMyResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlMyResultLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMyResultLayout.setVerticalGroup(
            pnlMyResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMyResultLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPlay.setText("Spela Igen");
        btnPlay.setEnabled(false);
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        lblAuthor.setText("Dennis Holm 2024-03-07");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRockPaperScissor, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlay)
                    .addComponent(pnlMyResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblAuthor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlRockPaperScissor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPlay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMyResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Aktivera knappen spela igen.
    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        /*tänder upp valknapparna. Tänder och återställer 
        datorns val och resultat-texten. Släcker spela igen-knappen. 
        Återställer räknare för datorns respektive spelarens vinster.*/
        btnRock.setEnabled(true);
        btnScissors.setEnabled(true);
        btnPaper.setEnabled(true);
        lblComputerChoice.setEnabled(true);
        txfResult.setEnabled(true);        
        btnPlay.setEnabled(false);

        lblComputerChoice.setText("");
        txfResult.setText("");
        
        nrHumanWin = 0;
        nrComputerWin = 0;
    }//GEN-LAST:event_btnPlayActionPerformed

    //Aktiverar valet "Sax"
    private void btnScissorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScissorsActionPerformed
        /*Efterfrågar ett slumpmässigt tal mellan 1-3 som översätts med ett
        switch-statement till Sten, sax eller påse. Detta är datorns val. */
        int computerNumber = random.nextInt(1,4);
        
        String computerChoice = "";
        switch (computerNumber) {
            case 1:
                computerChoice = "Sten";
                break;
            case 2:
                computerChoice = "Sax";
                break;
            case 3:
                computerChoice = "Påse";
                break;
        }      
        lblComputerChoice.setText(computerChoice);
        
        // Undersöker datorns val och tilldelar vinnaren 1 poäng.
        if ( computerChoice.equals( "Påse" ) ) {
            nrHumanWin++;
        } 
        else if ( computerChoice.equals( "Sten" ) ) {
            nrComputerWin++;
        }
        //Skriver ut resultatet.
        txfResult.setText( "Dator: " + nrComputerWin + " Spelare: "
                           + nrHumanWin);
        
        /*Läser av om datorn eller spelaren har kommit upp i 3 vinster.
        Om detta är sant släcks valknapparna ner tillsammans med informationen 
        om datorns val och resultat. Resultatet för omgången redovisas i 
        Mina resultat och knappen Spela igen tänds.*/
        if ( nrComputerWin > 2 || nrHumanWin > 2 ) {
            txaMyResult.append("Dator: " + nrComputerWin + " Spelare: " + 
                                nrHumanWin + "\n");
            btnRock.setEnabled(false);
            btnScissors.setEnabled(false);
            btnPaper.setEnabled(false);
            btnPlay.setEnabled(true);
            lblComputerChoice.setEnabled(false);
            txfResult.setEnabled(false);
        }
    }//GEN-LAST:event_btnScissorsActionPerformed
    //Aktiverar valet "Sten"
    private void btnRockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRockActionPerformed
        /*Efterfrågar ett slumpmässigt tal mellan 1-3 som översätts med ett
        switch-statement till Sten, sax eller påse. Detta är datorns val. */
        int computerNumber = random.nextInt(1,4);
        
        String computerChoice = "";
        switch (computerNumber) {
            case 1:
                computerChoice = "Sten";
                break;
            case 2:
                computerChoice = "Sax";
                break;
            case 3:
                computerChoice = "Påse";
                break;
        }
        lblComputerChoice.setText(computerChoice);
        
        // Undersöker datorns val och tilldelar vinnaren 1 poäng.
        if ( computerChoice.equals( "Sax" ) ) {
            nrHumanWin++;
        }
        else if ( computerChoice.equals( "Påse" ) ) {
            nrComputerWin++;
        }
        //Skriver ut resultatet.        
        txfResult.setText( "Dator: " + nrComputerWin + " Spelare: "
                           + nrHumanWin);
        
        /*Läser av om datorn eller spelaren har kommit upp i 3 vinster.
        Om detta är sant släcks valknapparna ner tillsammans med informationen 
        om datorns val och resultat. resultatet för omgången redovisas i 
        Mina resultat och knappen Spela igen tänds.*/
        if ( nrComputerWin > 2 || nrHumanWin > 2 ) {
            txaMyResult.append("Dator: " + nrComputerWin + " Spelare: " + 
                                nrHumanWin + "\n");
            btnRock.setEnabled(false);
            btnScissors.setEnabled(false);
            btnPaper.setEnabled(false);
            btnPlay.setEnabled(true);
            lblComputerChoice.setEnabled(false);
            txfResult.setEnabled(false);
        }
    }//GEN-LAST:event_btnRockActionPerformed
    //Aktiverar valet "Påse"
    private void btnPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaperActionPerformed
        /*Efterfrågar ett slumpmässigt tal mellan 1-3 som översätts med ett
        switch-statement till Sten, sax eller påse. Detta är datorns val. */        
        int computerNumber = random.nextInt(1,4);
        
        String computerChoice = "";
        switch (computerNumber) {
            case 1:
                computerChoice = "Sten";
                break;
            case 2:
                computerChoice = "Sax";
                break;
            case 3:
                computerChoice = "Påse";
                break;
        }
        
        lblComputerChoice.setText(computerChoice);
        
        // Undersöker datorns val och tilldelar vinnaren 1 poäng.
        if ( computerChoice.equals( "Sten" ) ) {
            nrHumanWin++;
        }
        else if ( computerChoice.equals( "Sax" ) ) {
            nrComputerWin++;
        }
        //Skriver ut resultatet.        
        txfResult.setText( "Dator: " + nrComputerWin + " Spelare: "
                           + nrHumanWin);
        
        /*Läser av om datorn eller spelaren har kommit upp i 3 vinster.
        Om detta är sant släcks valknapparna ner tillsammans med informationen 
        om datorns val och resultat. Resultatet för omgången redovisas i 
        Mina resultat och knappen Spela igen tänds.*/
        if ( nrComputerWin > 2 || nrHumanWin > 2 ) {
            txaMyResult.append("Dator: " + nrComputerWin + " Spelare: " + 
                                nrHumanWin + "\n");
            btnRock.setEnabled(false);
            btnScissors.setEnabled(false);
            btnPaper.setEnabled(false);
            btnPlay.setEnabled(true);
            lblComputerChoice.setEnabled(false);
            txfResult.setEnabled(false);
        }
    }//GEN-LAST:event_btnPaperActionPerformed
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inlamningsuppgift04().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaper;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnRock;
    private javax.swing.JButton btnScissors;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JTextField lblComputerChoice;
    private javax.swing.JLabel lblPaperTitle;
    private javax.swing.JLabel lblRockPaperScissor;
    private javax.swing.JLabel lblRockTitle;
    private javax.swing.JLabel lblScissorsTitle;
    private javax.swing.JPanel pnlMyResult;
    private javax.swing.JPanel pnlRockPaperScissor;
    private javax.swing.JTextArea txaMyResult;
    private javax.swing.JTextField txfResult;
    // End of variables declaration//GEN-END:variables
}
